### ISSUE TITLE
improve identity allocation and get constant uuid's

### ISSUE THREAD

**Issue by sixdiamants** [Airy59/Simple_RTM#1]
https://github.com/Airy59/Simple_RTM/blob/ab074d895edc7b737b4d6d198f59b9cb460855e8/Code/RTM_Base.py#L41

you may want to use python [uuid module](https://docs.python.org/3.8/library/uuid.html) instead of `id()`. Method uuid5(namespace, name) generates id's that depend on the arguments. So you always compute the same UUID *given a unique name*.

**Comment by Airy59** [comment]
Sounds great. Two objections:

1. BaseObjects have no name.
2. Unicity of IDs would become the responsibility of the user.

For 1., I could imagine workarounds: BaseObject never gets instantiated; NamedResource has a suitable name, and for others I could imagine solutions resting on overriding the BaseObject constructor. So objection is moot.

For 2., this is a major departure from RTM, but seems acceptable for a demonstrator, because ID consistency between successive outputs (from one user) matters, while ID unicity across outputs (from different users) does not.

So next update will follow your advice. Thanks.

**Comment by Airy59** [comment]
I've looked more deeply into your proposal. Problem is, the "Namespace" argument of uuid5 takes four possible values: URL, ISO OID, DNS, or X500 domain name. I'd rather have Python module name here, but no...
So I'd propose two possibilities:

- conform the RTM spec and generate UUIDs, using uuid.uuid4()
- set up an ad-hoc short, readable identification (of type string, e.g. str(autoinc) + object Name if any))

**Comment by sixdiamants** [comment]
>For the simple demo, I got it simpler :
IDs are autoinc. Fortunately, object creation order is deterministic, in Python (unlike garbage collection). So, run after run, objects get the same ID.

>The autoinc generator is a singleton.

Seems ok, this was only a suggestion for acquiring a semper idem id which you now achieved via a different means.
